## NOTICE: This file gets embedded into ibctest binary.
## Set the environment variable: IBCTEST_CONFIGURED_CHAINS to a path
## to use custom versions of this file

agoric:
  name: agoric
  type: cosmos
  bin: agd
  bech32-prefix: agoric
  denom: urun
  gas-prices: 0.01urun
  gas-adjustment: 1.3
  trusting-period: 672h
  images:
    - repository: ghcr.io/strangelove-ventures/heighliner/agoric
      uid-gid: 1025:1025
  no-host-mount: true

akash:
  name: akash
  type: cosmos
  bin: akash
  bech32-prefix: akash
  denom: uakt
  gas-prices: 0.01uakt
  gas-adjustment: 1.3
  trusting-period: 504h
  images:
    - repository: ghcr.io/strangelove-ventures/heighliner/akash
      uid-gid: 1025:1025
  no-host-mount: true

axelar:
  name: axelar
  type: cosmos
  bin: axelard
  bech32-prefix: axelar
  denom: uaxl
  gas-prices: 0.01uaxl
  gas-adjustment: 1.3
  trusting-period: 168h
  images:
    - repository: ghcr.io/strangelove-ventures/heighliner/axelar
      uid-gid: 1025:1025
  no-host-mount: true

bitcanna:
  name: bitcanna
  type: cosmos
  bin: bcnad
  bech32-prefix: bcna
  denom: ubcna
  gas-prices: 0.01ubcna
  gas-adjustment: 1.3
  trusting-period: 336h
  images:
    - repository: ghcr.io/strangelove-ventures/heighliner/bitcanna
      uid-gid: 1025:1025
  no-host-mount: true

bitsong:
  name: bitsong
  type: cosmos
  bin: bitsongd
  bech32-prefix: bitsong
  denom: ubtsg
  gas-prices: 0.01ubtsg
  gas-adjustment: 1.3
  trusting-period: 504h
  images:
    - repository: ghcr.io/strangelove-ventures/heighliner/bitsong
      uid-gid: 1025:1025
  no-host-mount: true

bostrom:
  name: bostrom
  type: cosmos
  bin: cyber
  bech32-prefix: bostrom
  denom: boot
  gas-prices: 0.01boot
  gas-adjustment: 1.3
  trusting-period: 192h
  images:
    - repository: ghcr.io/strangelove-ventures/heighliner/bostrom
      uid-gid: 1025:1025
  no-host-mount: true

carbon:
  name: carbon
  type: cosmos
  bin: carbond
  bech32-prefix: swth
  denom: swth
  gas-prices: 0.01swth
  gas-adjustment: 1.3
  trusting-period: 720h
  images:
    - repository: ghcr.io/strangelove-ventures/heighliner/carbon
      uid-gid: 1025:1025
  no-host-mount: true

composable:
  name: composable
  type: polkadot
  bin: polkadot
  bech32-prefix: ""
  denom: uDOT
  gas-prices: ""
  gas-adjustment: 0
  trusting-period: ""
  images:
    - repository: ghcr.io/strangelove-ventures/heighliner/polkadot
      uid-gid: 1025:1025
    - repository: ghcr.io/strangelove-ventures/heighliner/composable
      uid-gid: 1025:1025

gaia:
  name: gaia
  type: cosmos
  bin: gaiad
  bech32-prefix: cosmos
  denom: uatom
  gas-prices: 0.01uatom
  gas-adjustment: 1.3
  trusting-period: 504h
  images:
    - repository: ghcr.io/strangelove-ventures/heighliner/gaia
      uid-gid: 1025:1025
  no-host-mount: false

icad:
  name: icad
  type: cosmos
  bin: icad
  bech32-prefix: cosmos
  denom: photon
  gas-prices: 0.0photon
  gas-adjustment: 1.2
  trusting-period: 504h
  images:
    - repository: ghcr.io/strangelove-ventures/heighliner/icad
      uid-gid: 1025:1025
  no-host-mount: false

juno:
  name: juno
  type: cosmos
  bin: junod
  bech32-prefix: juno
  denom: ujuno
  gas-prices: 0.0025ujuno
  gas-adjustment: 1.3
  trusting-period: 672h
  images:
    - repository: ghcr.io/strangelove-ventures/heighliner/juno
      uid-gid: 1025:1025
  no-host-mount: false

osmosis:
  name: osmosis
  type: cosmos
  bin: osmosisd
  bech32-prefix: osmo
  denom: uosmo
  gas-prices: 0.0uosmo
  gas-adjustment: 1.3
  trusting-period: 336h
  images:
    - repository: ghcr.io/strangelove-ventures/heighliner/osmosis
      uid-gid: 1025:1025
  no-host-mount: false

penumbra:
  name: penumbra
  type: penumbra
  bin: tendermint
  bech32-prefix: penumbra
  denom: upenumbra
  gas-prices: 0.0upenumbra
  gas-adjustment: 1.3
  trusting-period: 672h
  images:
    - repository: ghcr.io/strangelove-ventures/heighliner/tendermint
      uid-gid: 1025:1025
    - repository: ghcr.io/strangelove-ventures/heighliner/penumbra
      uid-gid: 1025:1025