name: Local Interchain

on:
  pull_request:

# Ensures that only a single workflow per PR will run at a time. Cancels in-progress jobs if new commit is pushed.
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

env:
    GO_VERSION: 1.21

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    name: build-and-run
    defaults:
      run:
        working-directory: ./local-interchain
    steps:
      - name: Checkout interchaintest
        uses: actions/checkout@v3

      - name: Setup go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
            go-version: ${{ env.GO_VERSION }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install httpx --break-system-packages              

      - name: build local-interchain        
        run: go mod tidy && make install

      - name: Start background local-interchain        
        run: local-ic start base &

      - name: Run Python Script        
        run: python3 ./scripts/api_test.py

      - name: Cleanup        
        run: killall local-ic && exit 0